apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-peri
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-peri
    app.kubernetes.io/part-of: ey-app-node1
  name: devfile-sample-peri
  namespace: eyuen-tenant
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: devfile-sample-peri
    weight: null
status: {}
